[package]
name = "brain_rust"
version = "0.0.1"
authors = ["Ahmed Abdelwadod <me@ahmedwadod.com>"]
edition = "2018"
description = "BrainRust is Brainfuck to C compiler written in Rust."

[[bin]]
name = "brc"
path = "src/main.rs"

[dependencies]
